name: Create Static Pages from Notebooks
on:
  push:
    branches:
      - main

jobs:
  export-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:22
      options: --user node
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install create .venv
        run: |
          python3 -m venv .venv
          .venv/bin/pip3 install --upgrade pip

      - name: Install dependencies
        run: |
          npm install
          .venv/bin/pip3 install -r requirements.txt

      - name: Build static site
        run: npm run build

      - name: Push changes to static page repository
        run: |
          cd dist
          git init
          git config user.name "GitHub Actions"
          git config user.email ""
          git add .
          git commit -m "Update static pages"
          git remote add target "https://${{ secrets.TARGET_REPOSITORY_TOKEN }}@github.com/${{ vars.TARGET_REPOSITORY }}"
          git push target main
